### ISSUE TITLE
Process: Running the Largest Cities

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#107]
@gboeing @carlhiggs 

I have been able to successfully run through the process for 22 out of the 25 cities, and I have been able to run aggregation script for those 22 cities. Melbourne, Mexico City, and Seattle have not been running for me. I do not reach any error codes, but the code stops running and starts the next city after around 50-90 percent of the nodes are completed. The three cities have the largest graphml files of the 25, so it seems like a memory issue. My machine has 8gb of memory, so I tested this by changing my Docker preferences to 6gb. I then retested with 8gb. I deleted and redownloaded the data between each trial. The results are below

8gb (trial 1):
Melbourne:
- 94% node completion
- 2.44 seconds/node
- process_regions.sh: line 3: 135 killed

Mexico City:
- 84% node completion
- 2.14 seconds/node
- process_regions.sh: line 3: 143 killed

Seattle:
- 56% node completion
- 2.96 seconds/node
- process_regions.sh: line 3: 178 killed

6gb:
Melbourne:
- Killed (did not run)

Mexico City:
- Killed (did not run)

Seattle:
- Killed (did not run)

8gb (trial 2)
Melbourne:
- 85% node completion
- 2.63 seconds/node
- process_regions.sh: line 3: 14 killed

Mexico City:
- Killed (did not run)

Seattle:
- 52% node completion
- 8.74 seconds/node
- process_regions.sh: line 3: 27 killed

**Comment by gboeing** [comment]
Looks like this is an out-of-memory issue so I'm going to close this.
