### ISSUE TITLE
Geopandas / fiona Runtime warning

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#121]
[I don't believe this is urgent, or necessarily within our control to fix, but its an oddity worth noting]

Currently when we run our code (sp.py and aggr.py), there arises at several points RuntimeWarning errors; these apparently don't cause any issues in themselves, but they are disconcerting.

I believe the error arises when reading a layer from a geopackage, eg. in the calc_hexes_pct_sp_indicators() function on line 59 of aggr.py
![image](https://user-images.githubusercontent.com/12984626/122488642-3c5a9680-d021-11eb-96ec-f599ff089f2d.png)

this appears to relate to an update to the fiona package which Geopandas uses when reading in data.  I have found other threads discussing the issue, and that it appears to just be a performance warning not an error per se; I could not locate any fixes for addressing this:

https://stackoverflow.com/questions/64995369/geopandas-warning-on-read-file
https://github.com/Toblerity/Fiona/issues/986

The warning appears multiple times when running our code, so it would be nice if it could at least be suppressed.  However, i also don't think it is a priority (there is another issue with the code in aggr.py which appears to stop it running successfully, which I don't believe is related to this; so just logging this warning for reference to address later).

**Comment by gboeing** [comment]
Yep this is a common thing in recent months. I recommend just ignoring it and letting the dependencies sort themselves out in upcoming releases.
