### ISSUE TITLE
Can anyone get the data file?

### ISSUE THREAD

**Issue by meow0088** [healthysustainablecities/global-indicators#124]
Hello, I'm interesting in this project.
In the past few days, I have tried to make the code run successfully on my machine.
Now I'm wondering if it is convenient to get the dataset?
No matter what the answer is, I appreciate all of your work.
Thanks

**Comment by carlhiggs** [comment]
Hi @meow0088 ; we plan to publish this, but we haven't yet publicly as we've been focussing on the write up of a series of papers for publication.  However, I think you make a good point that it may be best to publish this with a DOI in a public repository sooner than later --- @gboeing , @shiqin-liu , @duelran , what do you think?  Perhaps we should check with our broader co-authors in the series.

I'll write an e-mail to the group now seeing what people think, but certainly we do plan to make this public.  We'll let you know what the plan is once its decided.

Thanks for engaging with the project,

Carl

**Comment by carlhiggs** [comment]
Just following up, the output data has now been uploaded to our institutional repsository at:
https://doi.org/10.25439/rmt.15072009.v1

This will be described in more detail in our forthcoming publication.  Hope this helps!

**Comment by meow0088** [comment]
I'm grateful for your update.
I'll find some times to give it a try.
Wish all of you have a good day.
