### ISSUE TITLE
01_create_study_region.py 

### ISSUE THREAD

**Issue by PreEnvirons** [healthysustainablecities/global-indicators#131]
When we execute 01_create_study_region.py, the defined boundaries  'boundaries.gpkg' is not found. Please see the following error notice:

Traceback (most recent call last):
Create study region boundary... 
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: .././data/boundaries.gpkg: No such file or directory

**Comment by carlhiggs** [comment]
Hi!  The boundaries geopackage has to be created by the user according to how they configure the project; I believe this is outlined in the article/supplementary material at the following links:
https://doi.org/10.1111/gean.12290
https://doi.org/10.1016/S2214-109X(22)00072-9

Having said that, the boundaries file we collated is downloadable from,
boundaries.gpkg: https://cloudstor.aarnet.edu.au/plus/s/DRrDHpEkgLDtulD
boundaries.gpkg.provenance.txt (metadata): https://cloudstor.aarnet.edu.au/plus/s/njdl6Uuv79UovQt

The boundaries file should be saved in the repository project path here:
global-indicators\process\data\boundaries.gpkg

Let me know how you go,

cheers,

Carl

**Comment by carlhiggs** [comment]
I am closing this as complete now as no response received from original poster.   A link to boundaries data was provided, and in addition this is available on CloudStor at https://cloudstor.aarnet.edu.au/plus/s/nYtHf1UqN9AAZX1
