### ISSUE TITLE
mdillon/postgis missing pgrouting

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#132]
Hi!

**ISSUE:** The [mdillon/postgis](https://hub.docker.com/r/mdillon/postgis/) docker image that is instructed in [process/pre_process/readme.md](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/readme.md) does not seem to include pgrouting which is required in the process. Using this image results in an error at least in [00_create_database.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/00_create_database.py), and later on in [03_create_network_resources.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/03_create_network_resources.py).

**FIX SUGGESTION:** I used [starefossen/pgrouting](https://hub.docker.com/r/starefossen/pgrouting) instead  - it is based on mdillon/postgis, but contains pgrouting readily installed. Probably not the only alternative but seems to work! 

I updated the instructions in [my fork, branch `helsinki`](https://github.com/VuokkoH/global-indicators/tree/helsinki/process/pre_process) where I'm testing to replicate the results for Helsinki :)

**Comment by carlhiggs** [comment]
Hi @VuokkoH --- thank you! there was an oversight in updating the readme.md, this was the PostGIS+pgRouting distribution used:
https://hub.docker.com/r/cityseer/postgis/tags

It looks like both starefossen and cityseer's docker images were compiled about 3 years ago --- but the cityseer one is PostgresSQL 11 with pgRouting 2.6, while starefossen's is PostgreSQL 10 with pgRouting 2.5

As we discussed separately, I am planning a large re-factor of the software to tighten up aspects like this (and how username/passwords are handled);  for now, if you did want to use the newer version, if you edit the below to match the user name and password configured for your project, this should work

docker pull cityseer/postgis
docker run --name=postgis -d -e PG_USER=user -e PG_PASSWORD=password -e DB_NAME=postgres -p 127.0.0.1:5433:5432 --restart=unless-stopped --volume=/var/lib/postgis :/postgresql/11/main cityseer/postgis:latest

I've updated the readme to reflect this, but I'll leave this issue open until I/others have had a chance to confirm more fully the updated directions are adequate until the process is re-factored/streamlined.

**Comment by carlhiggs** [comment]
I'm going to close this for now -- re-factoring will be a seperate process; I think updating the directions as already done was sufficient to resolve this
