### ISSUE TITLE
Deprecated function in 04_create_hex_grid.py?

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#133]
This if-clause results in an error in [04_create_hex_grid.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/04_create_hex_grid.py):

```
if not engine.dialect.has_table(engine, <tablename>)
   ...
```
This is the error message: 
```
Traceback (most recent call last):
  File "04_create_hex_grid.py", line 134, in <module>
    main()
  File "04_create_hex_grid.py", line 34, in main
    if not engine.dialect.has_table(engine, hex_grid):
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3319, in has_table
    self._ensure_has_table_connection(connection)
  File "/opt/conda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 348, in _ensure_has_table_connection
    "for public API use." % (Connection, type(arg))
sqlalchemy.exc.ArgumentError: The argument passed to Dialect.has_table() should be a <class 'sqlalchemy.engine.base.Connection'>, got <class 'sqlalchemy.engine.base.Engine'>. Additionally, the Dialect.has_table() method is for internal dialect use only; please use ``inspect(some_engine).has_table(<tablename>>)`` for public API use.
```

[I quick-fixed the issue by commenting out those if-clauses](https://github.com/VuokkoH/global-indicators/blob/helsinki/process/pre_process/04_create_hex_grid.py) (the SQL query anyway checks if table exists), but there is probably an easy fix also to the syntax. I'm not an sqlalchemy wizard so happy with my quick-fix for now :D

**Comment by carlhiggs** [comment]
Thanks for this Vuokko -- just acknowledging this formally in this thread as something I'll get around to updating soon-ish ; thanks for patience!
