### ISSUE TITLE
password protected cloudstor

### ISSUE THREAD

**Issue by guilhermeiablo** [healthysustainablecities/global-indicators#135]
I'm trying to run the notebooks but seem to be unable to access the CloudStor data without a password?

**Comment by carlhiggs** [comment]
Hi @guilhermeiablo , the prototype project in general was created to be run from scratch using source input data collated by analysts. For context, we are in the process of re-organising things to streamline the overall workflow to more readily extend for new analyses.

But to help with your specific question, if you provide the link to the part of the code which requires this data, it may be that I can check it out and could make the CloudStor data public.  It will help me if I can read the code to make sure I arrange access to the appropriate data, so please provide me with the link to the code and line itself if possible.

Also, you can access data outputs from the published 25 city analysis here: 

Higgs, Carl; Liu, Shiqin; Boeing, Geoff; Arundel, Jonathan; Lowe, Melanie; Adlakha, Deepti; et al. (2021): Global Healthy and Sustainable City Indicator Study Collaboration - 25 Cities spatial indicators datasets. RMIT University. Dataset. https://doi.org/10.25439/rmt.15072009 

Hope that's useful and makes sense,

Carl

**Comment by guilhermeiablo** [comment]
Oh, I see. I was actually asking because it was a part of the "analysis" read me, so I figured it was necessary. Thank you for the clarification!
The reason I was interested in looking at the files is because I'm having a hard time understanding whether the pre-processing scrips do the actual downloading from OSM and GHSL, and where to put the custom boundary files for cities. I see in the configuration excel spreadsheet the reference to a "dataset" folder but can't seem to find it.

**Comment by carlhiggs** [comment]
Hi Guilherme, I've just removed the password from that link --- the data hosted there (which includes copies of outputs and inputs, including GHSL data but only processed, not raw OSM) should be fully publicly accessible now.   Re data folder, I think you're referring to the folder 'data' which is a sub-folder of the process folder --- you can find that here: https://github.com/global-healthy-liveable-cities/global-indicators/tree/main/process/data

Hope this helps,

Carl
