### ISSUE TITLE
11_urban_covariates.py fails if changing intersection tolerance

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#137]
Tiny issue in 
- [11_urban_covariates.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/11_urban_covariates.py), [row 56](https://github.com/global-healthy-liveable-cities/global-indicators/blob/391c5e7fb1d95180d8dbd262e4aa54a7036e058d/process/pre_process/11_urban_covariates.py#L56)

- [_export_gpkg.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/_export_gpkg.py), [row 44](_export_gpkg.py)

Tolerance parameter in table name is "hard coded" as `12m`.  Fix would also require updating [_project_setup.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/_project_setup.py) which reads parameters from  [ _project_configuration.xls](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/_project_configuration.xls) where  the tolerance parameter can be changed.

I now quick-fixed it locally (config files might need bigger refactoring anyways as they are now a bit spread out here and there ;) )

**Comment by carlhiggs** [comment]
Thanks @VuokkoH  -- nice pick up!  I've just amended those two scripts to use the global intersection_tolerance parameter, which addresses this particular issue #137.

The bigger issue that this relates to, which we've seperately discussed is that city-specific tolerance should apparently be allowed (if not some kind of dynamic tolerance; but that may be beyond scope and over-complicated to implement).  I've just entered this as a new issue on the repository, #138. (i'll aim to address that in coming week)
