### ISSUE TITLE
Host-issue when connecting to pgrouting docker

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#162]
I had trouble connecting to the pgrouting/postgis docker with the instructed syntax in [process/README.md](https://github.com/global-healthy-liveable-cities/global-indicators/tree/main/process#3-run-docker). 

Depending on settings in `config.yml`, I got error "could not translate host name" (when `host: gateway.docker.internal` or `host: host.docker.internal` ) or "connection refused" (when `host: 127.0.0.1`) when running [process/pre_process/00_create_database.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/00_create_database.py). Also tried different variations of the docker run -command.

First, I thought I solved the issue by removing host from the docker run -command (just using syntax: `-p <host_port>:<container_port>`), and setting `host:0.0.0.0` in `config.yml` but then after a while this also did not work :D

Finally, thanks to [a link](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/61001152#61001152) from @carlhiggs , I got it working by using host ip `172.17.0.1`:

`docker run --name=postgis -d -e POSTGRES_PASSWORD=password -p 172.17.0.1:5433:5432 --restart=unless-stopped --volume=/var/lib/postgis:/postgresql/13/main pgrouting/pgrouting`

and setting host: `172.17.0.1` in `config.yml`.  

I am running this using Ubuntu 20.04 & Docker version 20.10.20.

I'm not sure if this is the "best practice" solution, but works for me. Could modify instructions so that this would work in most cases :) 

See these links for more information: 
- https://docs.docker.com/network/network-tutorial-standalone/
- https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/61001152#61001152

**Comment by carlhiggs** [comment]
Thank you for your testing of the updated software and for providing a workaround to this @VuokkoH!

It seems the local network port varies across different systems (eg Windows, Linux, Windows Subsystem for Linux, etc), so it would be great to develop an approach  to take some of the guesswork out of this.  Ultimately I'd like to get to a point where the various docker task environments (db, analysis, reporting, gui - if we make one) are launched from docker compose.  

As we discussed via e-mail, perhaps the approach mentioned in the link you shared above (https://stackoverflow.com/a/61001152/4636357), which queries the user's local IP address without making assumptions about what it is, could be a first step to achieving this.

Let's leave this issue open to remind us to give it a go when we get a chance!

**Comment by carlhiggs** [comment]
This issue also links to these other couple regarding simplifying the software setup process: 

- https://github.com/global-healthy-liveable-cities/global-indicators/issues/139
- https://github.com/global-healthy-liveable-cities/global_scorecards/issues/17

**Comment by carlhiggs** [comment]
I'll tentatively close this one @VuokkoH , as I believe the new approach sidesteps the issue by leaving host ip implicit when initialising the database (now done as part of running bash ./global-indicators.sh); as part of editing the config.yml the user may want to edit their IP to ensure it maps correctly (defaults to gateway.docker.internal; which may not be right for all systems and can be modified).   If you get a chance, love to hear if this works on your system as well!
