### ISSUE TITLE
File _gtfs_utils.py missing from the repo

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#163]
Hi! 

File `_gtfs_utils.py` seems to be missing from GitHub. This errors out in the new version of the gtfs analysis in [10_gtfs_analysis.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/10_gtfs_analysis.py#L21)

**Comment by carlhiggs** [comment]
Thanks Vuokko, I'll check this out when I get back to work next week (~5
December); some functions were consolidated, and though I tested things
out, some things (like this) could have been overlooked --- not all cities
have GTFS data so it's possible I could have missed the full testing ....
But I'll check it out next week :) Carl

**Comment by carlhiggs** [comment]
Thanks @VuokkoH; I've just added in this file (i had it local, but missed adding it when refactoring somehow).  I tested re-running Valencia GTFS and this appears to work as intended, so I'll close this one now!
