### ISSUE TITLE
Add in and use git pre-commit hooks with style checking

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#166]
We discussed that this would be a good idea, with a view to ultimately setting up unit and functional tests for continuous integration.   That can be done down the line, but this issue is just to mark the intent to set up and run git pre-commit hooks with flake8, black, pydocstyle etc.

**Comment by gboeing** [comment]
If it's a useful reference at all, here's the OSMnx pre-commit config: https://github.com/gboeing/osmnx/blob/main/.pre-commit-config.yaml
