### ISSUE TITLE
Add a utility script to remove a database

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#169]
A request was made for a utility script to remove a study region database, in particular to assist with debugging and test work (@VuokkoH ).   Its a good idea, although I'm not sure about over-automating file deletion -- its possible people (e.g. myself) could create and save various files in study region folders (eg maps) and over-eagerly purge the folder to start again, only to regret it later.  Perhaps in first instance I'll just make the script to drop the database (with manual confirmation prompt from user) and a reminder that any files should be manually removed.

**Comment by VuokkoH** [comment]
Thanks Carl! This sounds great! Very helpful when de-bugging and iterating the parameters. I ended up re-naming the regions to make sure I work with the latest settings when quickly re-running the analyses. Good if the tool promts for confirmation and indeed good not to over-automate this. However, I bet that each new region reguires a bit of trial and error before getting the settings straight so this will be a lot of help when doing that!
