### ISSUE TITLE
Update osmnx save_graph_shapefile() calls to use save_graph_geopackage()

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#171]
On the new enhancements branch we are using newer osmnx, which has some changed methods and some flagged as being deprecated --- this is one of those, so will be good to update while we're modifying things.   A nice to have.

```
/env/lib/python3.9/site-packages/osmnx/io.py:87: UserWarning: The `save_graph_shapefile` function is deprecated and will be removed in a future release. Instead, use the `save_graph_geopackage` function to save graphs as GeoPackage files for subsequent GIS analysis.
```

**Comment by gboeing** [comment]
Yes OSMnx is going this route: http://switchfromshapefile.org/

**Comment by carlhiggs** [comment]
I was just looking at implementing this, and reading the OSMnx feature request thread at https://github.com/gboeing/osmnx/issues/411#issuecomment-608125305 it occurred to me that we could bypass the gpkg (and the shapefiles; happy to be done with them!) and write directly to postgis, adapting Geoff's example.  

```
if not (db_contents.has_table('nodes') and db_contents.has_table('edges')):  
    print("\nPrepare and copy nodes and edges to postgis... ")          
    nodes, edges = ox.graph_to_gdfs(G)
    with engine.begin() as connection:
        nodes.to_postgis('nodes',connection,index=True)
        edges.to_postgis('edges',connection,index=True)
```

This simplifies the code considerably, makes the processing flow more logical, and should save time with reads and writes to files.   I've tested on one study region, and will try on others shortly.

**Comment by carlhiggs** [comment]
One difference i noticed in the postgis version loaded in this way was that it was missing the 'from' and 'to' columns.  These were present in the shape files, and the geopackage version.   

Looking at previous versions of edges and nodes that had these fields, as well as the u,v,key fields they are apparently derived from it seems that
- "from" is v and "to is u if key == 0 or key ==1
- "from" is u and "to" is v if key == 2

So, I'll recreate these fields as part of the network processing based on the above pattern.
