### ISSUE TITLE
Input data files should not be modified by the process; outputs should be clearly distinct

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#20]
(not urgent - but something for us to think about as we polish this code into the shape we want it to be)

I think its a bad idea that we modify our input data source files; we should aim to keep a clear distinction what is input and what is output.  Even if the layers in the geopackages aren't modified, we shouldn't add outputs to the input.  Doing this makes it unclear by looking at files if things have been processed.

A better approach might be to create a time stamped output geopackage, containing only the newly generated output layers.  

A naming convention could use a suffix like 'output-yyyy-mm-dd', like:

bangkok_th_2019_1600m_buffer_**output-2020-02-28**.gpkg

This would allow us to relate our outputs back directly to the date they were first generated (as file system date modified dates aren't always reliable, or standard across systems).  So, when we change our code for the in earnest outputs, we can tell at a glance when an output was generated so we can't get them mixed up.

Technically, the csv could be table in the output geopackage if we wanted to keep output resources contained in a single file (since a gpkg file is just an sqlite database); although that would just be a nicety to keep things tidy.

**Comment by shiqin-liu** [comment]
agree! will do
