### ISSUE TITLE
Record the software version (for reporting in metadata and reporting output, and cross-reference with Docker image tag)

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#245]
The version of the software used should be recorded in metadata output to enhance reproducibility.  This can also then be cross-referenced when we push software images to out Docker Hub organisation (https://hub.docker.com/orgs/globalhealthyliveablecities), to ensure our software releases clearly match up their paired analysis environment.

@gboeing provides some good examples for how to do this in the OSMnx repository, e.g. version is tracked in [settings.py](https://github.com/gboeing/osmnx/blob/2631b95a28300ccffce0c7c6838d269ce708ec1a/setup.py#L65) and a [Docker build shell script](https://github.com/gboeing/osmnx/blob/2631b95a28300ccffce0c7c6838d269ce708ec1a/environments/docker/docker-build.sh#L5-L6) is provided to facilitate tagging with version and date when building and pushing images to Docker Hub.

I think we should do similar here, as this will help mitigate potential future issues of users having mis-matched Docker image and software version.

**Comment by gboeing** [comment]
Agreed.
