### ISSUE TITLE
Refactoring project config

### ISSUE THREAD

**Issue by shiqin-liu** [healthysustainablecities/global-indicators#31]
In response to our early discussion on refactoring the config,  I have been working on creating a config python module to define project parameters and reduce the redundancies of the study region JSON file.  

With that, I created [setup_config.py](https://github.com/shiqin-liu/global-indicators/blob/master/process/setup_config.py) to define general project parameters. We can run this script to prepare each study region-specific parameters in JSON. I believe this makes the process of creating the config files more transparent and reproducible. So for example, if we want to make changes to general project parameters, we can just work with this  `setup_config.py`, rather than revising each individual study region JSON. 

So if we run `setup_config.py`, we will produce study region config like this for example [adelaide.json](https://github.com/shiqin-liu/global-indicators/blob/master/process/configuration/adelaide.json). I kept only the unique study region features in JSON and stores other repetitive parameters in `setup_config.py`. We can also import this config python module to reuse and define to parameters in the project scripts or notebook like [0_setup_config.ipynb](https://github.com/shiqin-liu/global-indicators/blob/master/process/0_setup_config.ipynb). 

I personally think that's a better approach to define config despite it is not perfect. Would love to hear your thoughts on this? Or anything other ways we can improve on?

I made a PR #30 with this update.

**Comment by carlhiggs** [comment]
Apologies for not commenting sooner Shirley; I think this is great, since as you point out many of the parameters are project- not city-specific.  I think this is a useful tool; thanks for taking the time to code it!

**Comment by gboeing** [comment]
@shiqin-liu I noticed this issue was still open. It appears to have been resolved by #30, correct? If so, that PR has been merged, so is it ok to close this issue now?

**Comment by shiqin-liu** [comment]
Yes! I think we can this issue.
