### ISSUE TITLE
City name not appearing when generating reports in "Portuguese - Brazil"

### ISSUE THREAD

**Issue by gigioLR** [healthysustainablecities/global-indicators#354]
**Describe the bug**
When we generate the reports in "Portuguese - Brazil", some sentences keep "São Paulo" instead of using the actual city name.

**Expected behavior**
All sentences in the report should use the analysed city name.

**Screenshots**
We noticed that some cells in the "Portuguese - Brazil" column ("_report_configuration.xlsx" > "languages" worksheet > "Portuguese - Brazil") still have "São Paulo" instead of {city_name}:

![image](https://github.com/global-healthy-liveable-cities/global-indicators/assets/79609240/02eadf96-e009-4a07-8c81-b871db5728fe)

**Additional context**
I edited the "_report_configuration.xlsx" file in Excel to address the issue and also adjusted some suboptimal translations observed.

File:
[_report_configuration_adjusted_Giovani.xlsx](https://github.com/global-healthy-liveable-cities/global-indicators/files/12162599/_report_configuration_adjusted_Giovani.xlsx)

**Comment by carlhiggs** [comment]
Hi @gigioLR , I see that hard-coded city names from the initial translations for our 25-city study is an issue for a few cities; thank you for picking up on this.  I'm making a start on an update to address this, and will let you know once this has been merged in the main branch.   Thank you for spotting and letting us know! Carl

**Comment by carlhiggs** [comment]
@gigioLR , would you mind testing out [this modified version](https://github.com/global-healthy-liveable-cities/global-indicators/raw/enhancements/process/configuration/templates/_report_configuration.xlsx) of the report configuration file that contains your corrections for the Brazilian Portuguese translation as well as some other languages with similar issues to confirm it works for your purposes?  If it does, I can merge the changes to the main branch after you confirm, although I am planning some other updates so will hold off until those are through to make a new release version of the software.

**Comment by gigioLR** [comment]
@carlhiggs, I absolutely can test it! I'll give you feedback by Friday.

**Comment by gigioLR** [comment]
Hi @carlhiggs , we tested here and it asks for the "template_web" worksheet, which is missing.

Report (web PDF template; English)
Traceback (most recent call last):
  File "/home/ghsci/process/generate.py", line 166, in <module>
    main()
  File "/home/ghsci/process/generate.py", line 162, in main
    r.generate()
  File "/home/ghsci/process/subprocesses/ghsci.py", line 123, in generate
    generate_resources(self)
  File "/home/ghsci/process/generate.py", line 142, in generate
    generate_report_for_language(
  File "/home/ghsci/process/subprocesses/_utils.py", line 317, in generate_report_for_language
    capture_return = generate_scorecard(
  File "/home/ghsci/process/subprocesses/_utils.py", line 1254, in generate_scorecard
    pages = pdf_template_setup(config, 'template_web', font, language)
  File "/home/ghsci/process/subprocesses/_utils.py", line 1024, in pdf_template_setup
    elements = pd.read_excel(
  File "/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 746, in parse
    sheet = self.get_sheet_by_name(asheetname)
  File "/env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 569, in get_sheet_by_name
    self.raise_if_bad_sheet_by_name(name)
  File "/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 597, in raise_if_bad_sheet_by_name
    raise ValueError(f"Worksheet named '{name}' not found")
ValueError: Worksheet named 'template_web' not found

**Comment by carlhiggs** [comment]
HI @gigioLR , I actually made quite a few additional changes to the templating yesterday --- so changes combined with code and the Excel file --- but I think if you are using the old code, it should still work if you open the Excel file and rename the worksheet "policy_spatial" to "template_web".  Its basically the same (some small difference to English prose).

It was a coincidence that yesterday I was already working on updating the spatial template, in addition to the translation aspect, and then my colleague Melanie got in touch about the redesign of the policy/spatial combined template (to use the new policy instrument).  It will probably take some time for all of this to work smoothly -- but if you do run the new code with the new spatial template, I think you will appreciate this.   It has a preview of a 'context' box that you can configure, and a more detailed study region map with satellite basemap.

Anyway - let me know how you go, and apologies for the mix up in that way.

**Comment by gigioLR** [comment]
Oh, I see. 

Our worry was that the error also happened using the latest release, but everything went well after the name change.

We are looking forward to test the new spatial/policy template!

Thanks, @carlhiggs !
