### ISSUE TITLE
Add a CITATION.cff file to the repo root

### ISSUE THREAD

**Issue by gboeing** [healthysustainablecities/global-indicators#419]
We should add a CITATION.cff file to the repo root to let users easily cite our software/reference paper: https://citation-file-format.github.io/ This will create a "Cite this repository" link in the repo's right sidebar.

See also [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citing-something-other-than-software), and especially:

> Extended CITATION.cff file describing the software, but linking to a research article as the preferred citation

**Comment by carlhiggs** [comment]
Great idea Geoff -- I didn't know about this, thanks for raising as an issue.  I could look into this next week, after I've sorted out the translations (trying to get these all sent out for validation this week; half done, but needing to focus on another project too).  Fingers crossed we hear about our manuscript soon (just checked and is still under review).

**Comment by carlhiggs** [comment]
Quick update; added in basic CITATION.cff for our software (https://doi.org/10.25439/rmt.24760260.v1); once our currently under review paper is published (fingers crossed for update soon!), we can update preferred citation.
