### ISSUE TITLE
Use the Github Wiki for FAQ and general documentation

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#422]
We should also consider moving the FAQ from the website (https://healthysustainablecities.github.io/software/#Frequently-Asked-Questions) to Github (e.g. https://github.com/global-healthy-liveable-cities/global-indicators/wiki) and use that as the central location for this and link to it.  But, rather than use that particular Wiki site, we should perhaps start it in a new repository in the https://github.com/healthysustainablecities organisation where we will migrate our software to.  In that way, we can document our longer term roadmap/plan.

The Wiki is recommended as 'a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together.'  Sounds like a useful idea for us moving forwards.  This will reduce the text on the website itself, so it is more instructional and less overwhelming (as per @eugenrb feedback).

Lets discuss this in our spatial team meeting next week @global-healthy-liveable-cities/software-spatial

**Comment by eugenrb** [comment]
I like this idea. I will try to join the next spatial team meeting, although it will be at 1 am. I still haven't been able to work on the software website mock, but I will be able to start working on this starting on the week of May 13th.

**Comment by gboeing** [comment]
+1 to moving the FAQ from the website to GitHub.

**Comment by carlhiggs** [comment]
I've set up a wiki with FAQ here: https://github.com/healthysustainablecities/global-indicators/wiki

potentially could have the full website there under different pages, but this is a start.

I've also set notifications on the readmes of this repository and the one under the new organisation (healthysustainablecities) that we will be migrating active development to the new organisation in line with our name.
