### ISSUE TITLE
Chinese characters in local data failed to be recognized by the software 

### ISSUE THREAD

**Issue by eugenrb** [healthysustainablecities/global-indicators#427]
I am adding this issue that was briefly described by Ke Peng who is analyzing Changsha:

"Among the eleven spatial indicators, the calculating results of three accessibility indicators using the open-source data offered by the Team differed greatly from real situation. We downloaded new destination data from local websites. Unfortunately, the local data contained Chinese characters that failed to be recognized by code operation. I am not sure whether Carl has solved this problem or not when I am writing this email. Xiaoyu will contact Carl tomorrow about the progress. If the “Chinese character”issue is solved, I believe Xiaoyu and I can complete the calculation of spatial indicators soon." 

@carlhiggs, I am adding it so you have this here on GitHub

**Comment by carlhiggs** [comment]
Thanks Eugen --- the e-mail from Ke Peng that I was cc'd in was the first i had heard of this issue, and we don't really know what the nature of it is yet.  Xiaoyu e-mailed me to confirm, she'll follow up on Friday and I'll assist her then.   At this stage, we don't know if this is an issue with software or a problem with configuration, or the source data.  It may be an issue on their side.   

Once I receive details about this and know what is going on, I'll update.

**Comment by carlhiggs** [comment]
Until we hear from Xiaoyu first hand details about what is being experienced and whether this actually relates to the software, I'm going to close this issue.  If it is a software related problem, we can re-open this then.
