### ISSUE TITLE
Docker / Docker Desktop 4.32.0 issues on Windows systems

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#465]
**Describe the bug**
The latest Docker Desktop version (4.32.0) has made the 'version' entry in docker-compose obsolete.

The file still launched for me, although @shiqin-liu who reported this to me on behalf of one of her students indicated the student couldn't get it to run.

Here is screen shot of me replicating the warning after updating Docker Desktop version, but the container launching regardless:
![image](https://github.com/user-attachments/assets/68880080-5130-4932-9c47-4d0dc0de4490)

So, what I'll try to do is update the docker-compose file to remove 'version' and see if that removes the warning.  If it does, i'll push that change which I believe will address this issue.

**Comment by carlhiggs** [comment]
@shiqin-liu can you let me know if the version just merged into main resolves the issue?  it seemed to remove the warning on my side, so I'm guessing all good?  I think perhaps in my screenshot above the Docker image worked because I stopped but didn't remove the existing image.  But the version must have succeeded building for the updated docker compose yaml to pass CI check; so I think this will resolve it. Fingers crossed!

**Comment by shiqin-liu** [comment]
@carlhiggs Thanks for addressing this, this is a good enhancement, things run well on my end. However, the issue that the student has seems like a different problem, she installed the latest software, but still doesn't run for her. The error she got is the `exec format error`, which is more likely related to the computer system architecture that is somehow not matching (see this post https://stackoverflow.com/questions/73285601/docker-exec-usr-bin-sh-exec-format-error). She did mention other students in the team have no issue starting the software, following the same steps.

**Comment by carlhiggs** [comment]
Hi @shiqin-liu , hmm seems strange; ours is/should be a multiplatform image, so should serve both amd64 (like I use) and arm64 (like you might use) architectures.  I am not sure that it is simply an issue with windows, as that's the platform I'm running. But I agree, will be important to find out what is causing this.

I am busy with another project today, but can look into this more tomorrow. 

In the mean time, can you ask the student to: 1) try again after first deleting the image in Docker desktop (in case they hadn't), and 2) provide more information on their computer system. 

I'm still hoping that a fresh start with step 1 might get it working; fingers crossed!

**Comment by shiqin-liu** [comment]
Hi @carlhiggs - I did ask the student to remove everything to start clean, and re-installed both docker and global-indicator software. And she was using the Windows 11 AMD64, and confirmed that she was installing the right docker version, which in theory shouldn't cause any surprise. But she is still not able to run. Below is her computer system information, if you notice anything let me know. 
<img width="599" alt="Screenshot 2024-07-18 at 1 31 59 PM" src="https://github.com/user-attachments/assets/53c5f42d-827e-425b-9b80-5eb2c45220a7">

**Comment by carlhiggs** [comment]
Hi @shiqin-liu , while I'm not sure about the specific cause of the issue that your student is facing, I suspect it could relate to incompatibilities introduced in the recent Docker Desktop update.   I updated Docker Desktop to 4.32.0 (I think i was running 4.29 perhaps, previously), and it wouldn't restart on my computer, and suspect this related to my WSL Ubuntu distribution (20.04) being [deprecated](https://docs.docker.com/desktop/release-notes/#deprecation) in 4.31.0.  I wasn't able to easily downgrade my Docker Desktop installation to test that theory though, so instead I was able to get things working by using `wsl --unregister [distro name]`.    Then, after running `wsl --install` to update with Ubuntu 22.04, Docker started successfully for me.  

I then removed my existing GHSCI docker containers and images and retrieved it anew by running the batch script as a test to see if our current Docker image with the change i made yesterday loads without issue using the latest Docker Desktop (4.32.0) version --- it worked without issue:
![image](https://github.com/user-attachments/assets/b1ce022a-8531-4eda-82c8-f915a0371456)

So --- to me this shows that what your student is experiencing isn't an issue with the Windows/AMD64 image.  However, I did experience issues using the latest Docker Desktop version with an older version of Ubuntu installed on WSL --- so if they are using Ubuntu 20.04, I would encourage them to unregister that and do a fresh install.  I tried just updating Ubuntu 20.04, but that didn't work -- unregistering and fresh install (of 22.04; the default up to date version that is installed when you enter 'wsl --install)) worked.

Sorry that I wasn't able to replicate the error your student has experienced, but perhaps give this a go and let me know how you go.

I will be looking into updating the Docker image dependencies today in any case; once the new image is built, uploaded, and retrievable through an updated version of our software they are welcome to give that a go too.  But I suspect that the issue isn't with our Docker image but something to do with the student's system.

**Comment by carlhiggs** [comment]
just an add on to the above, while I did get the latest Docker Desktop to start on my computer I experienced some instability --- I came back from lunch and found it had crashed despite not doing anything.  I wonder if it might be worth waiting for a patch (eg v4.32.1) before installing the latest Docker Desktop.   Again, this may not be the cause of the student's issue --- I can't be sure as I was unable to replicate it --- but if they are running Docker Desktop 4.32.0 it could be worth backstepping to an earlier version in case it is the source of instability, and not our software.
![image](https://github.com/user-attachments/assets/b27f4341-8d65-43f5-a85f-2a363b50b068)

**Comment by carlhiggs** [comment]
Hi @shiqin-liu, incidental to this issue, I've just updated our Docker image --- mostly to address dependabot alerts, but also updated to latest OSMnx, NiceGUI and geopandas.  Anyway --- I don't know what is causing the issue experienced by your student as I was unable to replicate it.  But hopefully between the suggestions in my previous post (ensure Ubuntu is updated for WSL2 if using latest Docker Desktop, possibly using a fresh install), and the new Docker image things should work better.  I am still waiting for our test pipeline to complete, but just wanted to flag this change in case its of interest.

Have a great weekend!

[oh, looks like the tests failed for the pull request;   Lucky we have additional tests! I'll have a look at that next week some time and polish it off then]

**Comment by carlhiggs** [comment]
Just a brief follow up --- it may or may not be related to the issues experienced by @shiqin-liu's student, but I continue to have issues with Docker Desktop crashing since upgrading to version 4.32.0 of Docker Desktop.  This is unrelated to our software; others using WSL report similar instability (e.g. https://github.com/docker/for-win/issues/14183 ).   I recommend not using installing the latest Docker Desktop (v4.32.0) for Windows users until it is patched to address whatever is causing the issue.

**Comment by carlhiggs** [comment]
Just an update on the Docker related issue I have been experiencing since updating to Docker 4.32.0 (and which may / may not have been a factor in @shiqin-liu's student's experience):  [according to Docker](https://docs.docker.com/desktop/release-notes/#known-issues), this may relate to installation of WSL 2.3.12.0.  They say that WSL v2.2.4.0 is required.  I will try to roll back and see if this addresses my issues (which are now sporadic; Docker Desktop occasionally crashing/not starting up).  However, [multiple users](https://github.com/microsoft/WSL/issues/11794) have now suggested that reverting to WSL 2.2.4.0 doesn't address the issue, so may need to wait for Docker to actually address the bug for Windows, hopefully soon.

-- update: for now, instead of attempting a roll back of WSL, I've updated Docker Desktop to 4.33.0 to see if that will work with WSL 2.3.12.0 that I currently have installed.  It started successfully, which is more than was happening previously, so --- so far so good.  If I have issues, I'll add to this thread; otherwise, I'll close it.

**Comment by carlhiggs** [comment]
Hi @shiqin-liu, any updates from your student?  I don't know if the Docker Desktop version was a factor in the issue you initially reported them experiencing, but things seem to be going fine with latest Docker Desktop (v4.33.0) using latest WSL and Ubuntu for me on Windows, and using our latest Docker image.  Let me know if any more issues and we'll keep this thread open to investigate, else, I'll close it as resolved.

**Comment by shiqin-liu** [comment]
> Hi @shiqin-liu, any updates from your student? I don't know if the Docker Desktop version was a factor in the issue you initially reported them experiencing, but things seem to be going fine with latest Docker Desktop (v4.33.0) using latest WSL and Ubuntu for me on Windows, and using our latest Docker image. Let me know if any more issues and we'll keep this thread open to investigate, else, I'll close it as resolved.

@carlhiggs sorry for the late response, we are pretty sure at this point the student's issue is not related to the docker version, though she is still not able to run the docker image on her own labtop but she was able to do so in another computer, and other students in the team have successfully started the software as well. The docker updates look great, it works well on my end too. So feel free to close this when ready.
