### ISSUE TITLE
Add guidance where to save the folders to FAQ [to avoide issues with too long file paths] 

### ISSUE THREAD

**Issue by zarayousefi** [healthysustainablecities/global-indicators#469]
If we download and put the unzip file in the long path files it may not extract all the files because the directory could be too long. 

We should provide some guidance to people to save and run the software in the shorter file path.

**Comment by carlhiggs** [comment]
@zarayousefi I think you may have addressed this in the FAQ now (thank you!); if you have can we mark this issue closed?
