### ISSUE TITLE
Why is an indicator(s) missing from the policy report, even though it was identified in the data file

### ISSUE THREAD

**Issue by zarayousefi** [healthysustainablecities/global-indicators#486]
Hi @carlhiggs @eugenrb @ruoyuch 
Is this ok to add to FQA?
This issue may occur if cells in Column A (Indicators) of the policy checklist have been unmerged. The software relies on merged cells in this column to correctly interpret the data. If the cells were unmerged when adding new rows, re-merge them to resolve the issue.

**Comment by carlhiggs** [comment]
I think this guidance is good but the issue could be written more generally/simply as "**Why does the policy report not generate as intended?**"

We could advise that:

> The policy checklist Excel file is a template, and any modifications (for example, unmerging cells) can result in issues with analysis, formatting, or successful generation of a policy report.  

> When adding new rows to record additional policies that have been reviewed, ensure that existing rows do not unmerge.  To do this, right click on the row number of an existing row within the indicator (Column A) that you are adding a new row, and click 'insert'.  This should add a new row within that indicator, above the selected row and without unmerging existing cells.

It could be useful to phrase in this way to make clear that in general, the formatting of the template should not be changed.  This can have unpredictable consequences, and only the official template when used as intended is supported.

**Comment by zarayousefi** [comment]
Thank you @carlhiggs I added it to the FQA.

**Comment by carlhiggs** [comment]
Thanks @zarayousefi , has this issue been addressed now?  Just wanted to check in case we can close it :)

**Comment by zarayousefi** [comment]
Hi @carlhiggs 
Yes, I added it to the FAQs. Will close it. 
Wasn't familiar with this part to close!
