### ISSUE TITLE
ox.basic_stats: ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by shiqin-liu** [healthysustainablecities/global-indicators#5]
I was trying the rerun the create sausage buffer analysis with complete sample points in [04_create_sausage_buffer.ipynb](https://github.com/shiqin-liu/global-indicators/blob/phoenix/process/04_create_sausage_buffer.ipynb).  

```
#create sausage buffer local neighborhood graph
def create_sausage_buffer_G(G_proj, orig_point, buffer=50, length = 1600, intersection_tolerance = 15):  
     # locate closest node on network to 
     orig_node = ox.get_nearest_node(G_proj, orig_point, return_dist=True)
    subgraph_proj = nx.ego_graph(G_proj, orig_node[0], radius=length, distance='length')
    # create buffer
    subgraph_gdf = ox.graph_to_gdfs(subgraph_proj, nodes=False, edges=True, fill_edge_geometry=True)
    buffer = subgraph_gdf.geometry.buffer(buffer)
    buffer_uu = buffer.geometry.unary_union
    return([subgraph_proj, buffer_uu])

# Local neighbourhood analysis
def analyse_local_nh(G_proj, orig_point):
    buffer = create_sausage_buffer_G(G_proj, orig_point)
    orig_node = ox.get_nearest_node(G_proj, orig_point, return_dist=True)
    #get stats
    area_sqm = buffer[1].area
    area_sqkm = area_sqm*1e-06
    stats = ox.basic_stats(buffer[0], area=area_sqm, clean_intersects=True, circuity_dist='euclidean')
    return({ 'origin_node_id': orig_node[0],
             'area_sqkm': area_sqkm,
             'stats': stats,
             'origin_node_snap_dist': orig_node[1]})
```
I was getting the error `not enough values to unpack (expected 2, got 0)` when running the function half-way with points:  

```
for point in point_locations:
    nh_estimates.append(analyse_local_nh(G_proj, point))
```

here is the error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-53eab403d6c0> in <module>
      4 nh_estimates1 = []
      5 for point in point_locations[530:531]:
----> 6     nh_estimates1.append(analyse_local_nh(G_proj, point))
      7 

<ipython-input-10-908ea04127aa> in analyse_local_nh(G_proj, orig_point)
      6     area_sqm = buffer[1].area
      7     area_sqkm = area_sqm*1e-06
----> 8     stats = ox.basic_stats(buffer[0], area=area_sqm, clean_intersects=True, circuity_dist='euclidean')
      9     return({ 'origin_node_id': orig_node[0],
     10              'area_sqkm': area_sqkm,

~/miniconda3/envs/asa/lib/python3.7/site-packages/osmnx/stats.py in basic_stats(G, area, clean_intersects, tolerance, circuity_dist)
    144     # calculate clean intersection counts
    145     if clean_intersects:
--> 146         clean_intersection_points = clean_intersections(G, tolerance=tolerance, dead_ends=False )
    147         clean_intersection_count = len(clean_intersection_points)
    148     else:

~/miniconda3/envs/asa/lib/python3.7/site-packages/osmnx/simplify.py in clean_intersections(G, tolerance, dead_ends)
    345     # create a GeoDataFrame of nodes, buffer to passed-in distance, merge
    346     # overlaps
--> 347     gdf_nodes = graph_to_gdfs(G, edges=False)
    348     buffered_nodes = gdf_nodes.buffer(tolerance).unary_union
    349     if isinstance(buffered_nodes, Polygon):

~/miniconda3/envs/asa/lib/python3.7/site-packages/osmnx/save_load.py in graph_to_gdfs(G, nodes, edges, node_geometry, fill_edge_geometry)
    534         start_time = time.time()
    535 
--> 536         nodes, data = zip(*G.nodes(data=True))
    537         gdf_nodes = gpd.GeoDataFrame(list(data), index=nodes)
    538         if node_geometry:

ValueError: not enough values to unpack (expected 2, got 0)
```

I have noticed it was the clean_intersection issue, I traced back to the point where it gets me the error, the point connects to a subgraph with only two nodes and one segment with no clean intersection.  How to deal with this issue? Should I create a condition inside functions to filter out those points?
![temp](https://user-images.githubusercontent.com/46453772/63389343-700efb80-c379-11e9-9395-05d93d969d73.png)

**Comment by carlhiggs** [comment]
Hi Shirley,  

The first thought that comes to my mind with this is, it looks like intersection cleaning is being done for each sub-graph excerpt; however, I think it might make more sense to run the clean intersections once for the full G_proj network (which in itself should have had retain_islands set to False, so should have no orphan segments like these).  So, then when running the local neighbourhood analyses,  instead of running basic_stats, we could use Geopandas to count how many clean intersections (of the full network) are located within the 1600m buffered network segment, and then use that number relative to the area to get the intersection density statistic.

I might be missing the point here - but I'm curious if that helps! Please let me know if I've totally misunderstood the issue.

Apologies for silence on my end for a while; I have been catching up with other projects.  I will try to devote more time to this project in the coming month and moving forwards.

**Comment by shiqin-liu** [comment]
Thank you, Carl! It seems like a solution to count clean intersections directly for each buffered network. I was just thinking if I could still use .basic_stats since some of the basic stats may be useful to keep as well. Maybe I could create a conditional statement to rule out the buffered network where intersection count is zero, and run .basic_stats for those buffered network with clean_intersections=False; that way I can still use the function and retain all other stats. I am still testing this approach. If it does not work, I will try the solution as you mentioned. Sorry for not responding sooner, I was trying to run codes for the entire network lately but it was slow due to the performance issues of my computer.

And no worry for the silence, I was basically cleaning and rerunning the scripts these weeks, may need some times to sort out the "mess." Hope to give you more updates soon. Thank you again!
