### ISSUE TITLE
validation readme

### ISSUE THREAD

**Issue by gboeing** [healthysustainablecities/global-indicators#50]
@nicholas-david it looks like the [readme](https://github.com/gboeing/global-indicators/blob/master/validation/readme.md) in the validation folder is outdated? It references downloading data from the google drive rather than cloudstor, and its directions are unclear as to how to organize the downloaded files to run the validation notebooks.

**Comment by gboeing** [comment]
Oh also: do you know why the file is called `belfast_gb_2019_10000m_all_osm_20190902.graphml.xml`? That's a graphml file, not an xml file... but someone gave it an xml file extension... any ideas?

**Comment by nicholas-david** [comment]
You are right, I will update the readme before Monday. 

And I changed it to have the .XML because that is what the file is called on my machine. I am not sure why my file changed though. 

Please let me know if there is anything else I can do for Monday.

**Comment by gboeing** [comment]
Thanks! I'm taking a pass through code clean up in #51. I'll ping you there when the progress is wrapping up so you can take a look.

**Comment by gboeing** [comment]
Ok, it turned into a bigger refactoring project, but #51 is done and merged. @nicholas-david and @DRosasMoctezuma could you please both review the newly updated [edge validation folder](https://github.com/gboeing/global-indicators/tree/master/validation/edge) anytime prior to next Monday's zoom? I had a re-think of how we were doing it and made a few changes including:

  - no more notebooks: a single script processes everything now
  - updated the functions and internal operation
  - all calculations are either saved as images to disk or as a CSV file of indicators to disk
  - configs are moved to the validation root folder where they can (and should) be shared with the destinations validation script

I'd like you to update the destinations folder similar to how this edge validation folder now works, next week. We can discuss on the call. @nicholas-david the readme(s) still needs to be updated, per the first comment in this issue... but perhaps that should wait until all this clean up is finished. Thanks!

**Comment by nicholas-david** [comment]
@gboeing What was the reasoning behind moving the configuration folder? For reproducing this for the destination validation, there are different configuration files that we need. The currently exist in the destination folder.

**Comment by gboeing** [comment]
> What was the reasoning behind moving the configuration folder? For reproducing this for the destination validation, there are different configuration files that we need. The currently exist in the destination folder.

Yep. I haven't taken a crack at revising the destination folder yet, but the configs in `/validation/destination/configuration` can be merged into the files in `/validation/configuration` so we have unified configuration files.

**Comment by gboeing** [comment]
> the configs in /validation/destination/configuration can be merged into the files in /validation/configuration so we have unified configuration files

@nicholas-david this is now finished and merged into master via #52

**Comment by gboeing** [comment]
@nicholas-david I forgot to mention it on the call, but renaming the XML files (see top of this issue) is also an action item for this week. @DRosasMoctezuma would you like to tackle that? You'd have to:

  1. Rename all the `*.graphml.xml` data files to just `*.graphml`
  2. Update the validation/configuration json files to point to their correct renamed paths
  3. Open commit the edited configuration json files and open a PR

This could be an easy 1st PR for you and it would close this issue.
