### ISSUE TITLE
Destination Validation: Paring Down

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#57]
Hey everyone,

David and I have been looking closer into the official datasets from Sao Paulo, Olomouc, and Belfast. Right now, we are trying to 'pair down' the datasets so that we are able to make more 'apples to apples' comparisons between the official and OSM derived datasets. 

**Sao Paulo:**
Sao Paolo's official dataset has 939 destinations (point data) as shown below. 

![SaoPaulo](https://user-images.githubusercontent.com/60232046/86401937-e3eb8700-bc5f-11ea-9600-62aadd49ba35.png)

There are category labels, so we were able to sort out the relevant categories of data. After sorting, there are 34 relevant destinations. 

**Olomouc:**
Olomouc's official dataset has 63 destinations (point data) as shown below.

![Olomouc](https://user-images.githubusercontent.com/60232046/86401977-f6fe5700-bc5f-11ea-9dfb-d3a511ab18fc.png)

There is no category label, so we are unable to systematically sort thru the data. Looking at it manually, however, it does seem to be that each of the points is a supermarket (we looked at about 10). 

We think that means that we can just use all the Olomouc data for the apples to apples comparison.  

**Belfast:**
Belfast's official dataset has 1,479 destinations (polygon data) as shown below.

![Belfast](https://user-images.githubusercontent.com/60232046/86401394-fb764000-bc5e-11ea-9511-5025a83f3288.png)

For Belfast, there is no name or category data, so we are unsure how to sort out food-related destinations that are out of scope (like farmer's markets and restaurants). Does anyone have ideas?

Additionally, should we think of different ways to validate data, considering that it is polygon data instead of point data? 

**For Coding:**
@gboeing On our call on Tuesday, you advised us to make sure that the config files were updated for each city so that the relevant destinations could be extracted. Considering that this can be done for only one of the three cities, should we change our approach?

**Comment by gboeing** [comment]
What about adding a dict to the json configs like this:

```javascript
destination_fields : {"field_name" : ["category1", "category2"]}
```

For each city's json file, the "field_name" would be the column in the shapefile to identify destination types. Multiple can be added to that dictionary. Its value is a list of acceptable values in that column to retain. If is is `None`, then retain all rows. That allows the code to stay agnostic to the structure of the shapefiles for each city, while allowing flexible dynamic filtering as needed (especially if we need to expand this in the future).

**Comment by gboeing** [comment]
@nicholas-david what's the status of this issue?

**Comment by nicholas-david** [comment]
@gboeing Hey, I am working on this now. I have created the dictionaries in the config files, but I am having a hard time getting these dictionaries to actually apply to the datasets.

**Comment by gboeing** [comment]
closed by #64

**Comment by gboeing** [comment]
@nicholas-david I fixed the destinations col/val filtering you got stuck at in #65. It works for Sao Paulo. Can you propagate this solution to the other json config files and ensure it's working across all destination validation cities?

**Comment by gboeing** [comment]
@nicholas-david did the PRs we merged this week fully resolve this issue? If so, you can close it.
