### ISSUE TITLE
[BUG] writing to wrong geopackage file?

### ISSUE THREAD

**Issue by gboeing** [healthysustainablecities/global-indicators#77]
@shiqin-liu there appears to be a bug in `/process/sp.py` on [this line](https://github.com/gboeing/global-indicators/blob/48a2ed667dd78ba6eed3817a66aa68328c665d72/process/sp.py#L307), but I want to confirm with you.

Specifically, it saves the "samplepointResult" results layer to `gpkgPath` rather than `gpkgPath_output`. This means that the results are being saved to the input file, such as `olomouc_cz_2019_1600m_buffer.gpkg` but it appears that they should be getting saved to the output file instead, such as `olomouc_cz_2019_1600m_buffer_output20200402.gpkg`, right?

For example, running `aggr.py` throws an exception, because it cannot find the "samplepointResult" layer in  `olomouc_cz_2019_1600m_buffer_output20200402.gpkg`.

**Comment by gboeing** [comment]
Proposed fix in e3667b2 which I've included in PR #76.

**Comment by gboeing** [comment]
Ok just finished testing the proposed fix and can confirm `aggr.py` works now.

**Comment by shiqin-liu** [comment]
Yes! the output should be saved in gpkgPath_output. Sorry, I just see that, it looks like you fixed this, Thanks!!
