### ISSUE TITLE
Official Destination Data

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#79]
Hi All, 

For the destination data received from Olomouc and Sao Paolo, are we aware of how the destination was chosen to be represented? For example, does each point represent the centroid of the parcel that the destination lies within?

**Comment by gboeing** [comment]
I'm not sure. But that'd be my guess. @carlhiggs any ideas?

**Comment by carlhiggs** [comment]
Hi Nick, sorry for delay on response --- it wasn't specified, but where the data are point data, it is assumed they are centroids (e.g. as doorways would be implausibly precise to represent; if not centroids, it is assumed the difference would be arbitrary).

Looking at the data from Olomouc just now, it looks like these are points; whereas the shape of the data provide from Sao Paulo depended on the destination (eg. while supermarkets may be points, there were polygons for parks or forest, or lines for routes, etc).

Hope that helps,

Carl

ps. here is metadata for the Sao Paulo data we were provided
[metadata.xlsx](https://github.com/gboeing/global-indicators/files/5066903/metadata.xlsx)

**Comment by carlhiggs** [comment]
Also, here are metadata for the Olomouc POI data (which is associated with a category variable ID_KAT; this is explained in English in this file):
[Olomouc_POI_2011_ID_Categories_explanation - Jan DYGRÝN.docx](https://github.com/gboeing/global-indicators/files/5066921/Olomouc_POI_2011_ID_Categories_explanation.-.Jan.DYGRYN.docx)

**Comment by carlhiggs** [comment]
Apologies for repeat answers --- but worth noting the time points for data; the metadata for Olomouc was for the 2011 POI file, but I believe for validation you used the 2018 supermarkets specific data.   For Sao Paulo, dates for various datasets are provided in the Excel spreadsheet; grocery stores also seem to be 2018 for Sao Paulo.

**Comment by carlhiggs** [comment]
hi @nicholas-david , not sure if you saw these responses when posted last month - just flagging in case these were missed!

**Comment by gboeing** [comment]
Thanks Carl. Nick can you verify that any relevant details in these metadata appear in the validation report? Thanks!

**Comment by nicholas-david** [comment]
Thanks Geoff! Will do. Just a heads up, I will not be as contactable or put as much time in this weekend for the High Holidays. Have a nice weekend!
