### ISSUE TITLE
Probably unimportant, but warning message when running git pull re absent ref

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#80]
When running the docker batch script which included a git pull command, the warning came up

_Your configuration specifies to merge with the ref 'refs/heads/full_dist_function' from the remote, but no such ref was fetched._

I expect this probably isn't an issue that will impact things, but in case it hadn't been noted, sharing here (not sure how to address this myself).

**Comment by gboeing** [comment]
If you checkout master locally, then git pull does that fix it? That branch was merged and deleted at the remote so the warning makes sense.

**Comment by carlhiggs** [comment]
Thanks Geoff --- sorry, I didn't realise that I probably wasn't on master; you're right that was likely the last branch I was on, hence error -- i'll close this!
